
exclude: ['.rvmrc', '.rbenv-version', 'README.md', 'changelog.md', 'bin', 'vendor', 'Gemfile', 'Gemfile.lock', 'Procfile', 'Rakefile', 'unicorn.rb', 'config.ru']
auto: false
pygments: true

# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
title_suffix: Abhishek Munie
tagline: 
author :
  name : Abhishek Munie
  email : contact@abhishekmunie.com
  github : abhishekmunie
  twitter : abhishekmunie
publisher : https://plus.google.com/101030613278833301135

production_url : http://abhishekmunie.com
development_url : http://nightly.abhishekmunie.com

ASSET_PATH :
  img : http://s.abhishekmunie.com
  css : http://css.abhishekmunie.com
  js : http://js.abhishekmunie.com
  static : http://s.abhishekmunie.com

mySite_config :
  facebook :
    appid : 119876094728323
  addThis:
    id : abhishekmunie
  google :
    analytics :
      domainGA_ID : UA-16273870
    CSEId : '018183667250833623538:fysqqstan_i'
    CSEAutoCompletionId : '018183667250833623538:fysqqstan_i+qptype:1'